### ISSUE TITLE
集成百度地图

### ISSUE THREAD

**Issue by wangyankun33** [jingliancui/XamarinLibraryMenu#3]
可以集成百度地图android sdk吗？或者集成百度地图 android jar，android aar

**Comment by jingliancui** [comment]
由于百度没有采用gradle的形式分包，所以我以前绑了一个全功能的包后就再没有绑百度地图的包了。你可以考虑用高德地图的包，也可以翻一下我的nuget，名字很长那个就是百度地图全功能的包。

**Comment by jingliancui** [comment]
https://mp.weixin.qq.com/s/RMFbCG2ldJ5U-05u1lS8gA

参考这个，现在可用了。
